name: run shell commands
on: [push]
jobs:
  run-shell-command:
    run-on: ubuntu latest
    steps:
      - name: Echo a string
        run: echo "hello security gurus this is our first github actions workflow file"